name: ci-cd pipeline

on:
  push:
    branches:
      - main
env:
    GKE_CLUSTER: cluster-1   
    GKE_ZONE: us-central1-a
jobs:
  docker-image:
    runs-on: self-hosted
    permissions:
        packages: write

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
           registry: ghcr.io
           username: ${{ github.repository_owner}}
           password: ${{ secrets.GITHUB_TOKEN}}
        
      - name: Buildx Action
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: |
              ${{ vars.DOCKER_USERNAME }}/nodeapp:${{ github.sha}}
              ghcr.io/${{ github.repository_owner }}/nodeapp:${{ github.sha}}
   
  deploy:
    needs: docker-image
    runs-on: self-hosted

    steps:
        - name: Repo Checkout
          uses: actions/checkout@v4

        - name: Install kubectl CLI
          uses: azure/setup-kubectl@v4
        
        - name: GCP Authentication
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GKE_SA_KEY }}

        

