name: ci-cd pipeline

on:
  push:
    branches:
      - main
env:
    GKE_CLUSTER: cluster-1   
    GKE_ZONE: us-central1-a
jobs:
  docker-image:
    runs-on: self-hosted
    permissions:
        packages: write

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
           registry: ghcr.io
           username: ${{ github.repository_owner}}
           password: ${{ secrets.GITHUB_TOKEN}}
        
      - name: Buildx Action
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: |
              ${{ vars.DOCKER_USERNAME }}/nodeapp:${{ github.sha}}
              ghcr.io/${{ github.repository_owner }}/nodeapp:${{ github.sha}}
   
  deploy:
    needs: docker-image
    runs-on: self-hosted

    steps:
        - name: Repo Checkout
          uses: actions/checkout@v4

        - name: Install kubectl CLI
          uses: azure/setup-kubectl@v4

        - name: gcloud Setup
          uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
          with:
           service_account_key: ${{ secrets.GKE_SA_KEY }}
           project_id: ${{ secrets.GKE_PROJECT }}
        
        - name: Get GKE Credentials
          uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
          with:
           cluster_name: ${{ env.GKE_CLUSTER }}
           location: ${{ env.GKE_ZONE }}
           credentials: ${{ secrets.GKE_SA_KEY }}
        
        - name: Get GKE nodes
          run: kubectl get nodes

