name: ci-cd pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-image:
    runs-on: self-hosted
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
           registry: ghcr.io
           username: ${{ github.repository_owner}}
           password: ${{ secrets.GITHUB_TOKEN}}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tag: |
              ${{ vars.DOCKER_USERNAME }}/nodeapp:${{ github.sha}}
              ghcr.io/${{ github.repository_owner }}/nodeapp:${{ github.sha}}


